clear all;
clc;

%% read table
gene_exp = readtable('./SuppTables_v2.xlsx');
gene_exp_array = table2array(gene_exp(:,2:end));

%% plot

figure();
hold on;
time = [[0.6,4,20,40,60,90,120]/60,6.3,10.5,15,48]; % h first 0.6 should be zero

gnames = {'Ipd';'fhuA';'fhuC';'fhuD';'fhuB';...
              'glnD';'cyoA';'cyoB';'cyoC';'cyoD';...
              'cyoE';'glnK';'amtB';'fepA';'entD';...
              'fes';'ybdZ';'entF';'fepE';'fepD';...
              'fepG';'fepC';'entS';'RutR';'fepB';...
              'entC';'entE';'entB';'entA';'entH';...
              'sdhC';'sdhD';'sdhA';'sdhB';'gpmA';...
              'fiu';'aspC';'ompF';'pyrC';'fhuE';...
              'ndh';'oppA';'oppB';'oppC';'oppD';...
              'oppF';'tonB';'fnr';'nohA';'ydfN';...
              'tfaQ';'fumC';'purR';'sufA';'sufB';...
              'sufC';'sufD';'sufS';'sufE';'katE';...
              'gdhA';'mntP';'zwf';'Fur';'flhD';...
              'flhC';'ftnA';'zinT';'nac';'gnd';...
              'rcnA';'rcnB';'cirA';'mntH';'hmp';...
              'grcA';'nrdH';'nrdI';'nrdE';'nrdF';...
              'rpoS';'exbD';'exbB';'nfeF';'garP';...
              'garL';'garR';'garK';'rnpB';'gltB';...
              'gltD';'gltF';'gspC';'gspD';'gspE';...
              'gspF';'gspG';'gspH';'gspI';'gspJ';...
              'gspK';'gspL';'gspM';'gspO';'feoA';...
              'feoB';'feoC';'ryhB';'yhhY';'sodA';...
              'metJ';'katG';'metH';'soxS';'soxR';...
              'fumB';'fecA';'fecB';'fecC';'fecD';...
              'fecE';'fecI';'fecR';'fhuF';'yjjZ'};
cls = jet(size(gnames,1));
exist_genes = {};
count=1;
for i=1:size(gnames,1)
    expression = gene_exp_array(find(strcmp(gene_exp.Var1,gnames{i})),:);
    if (~isempty(expression))
        for j=1:size(expression,1)
            exist_genes{count} = gnames{i};
            plot(time,expression(j,:),'-','Color',cls(i,:));
            count=count+1;
        end
    end
end
legend(exist_genes);

set(gca,'Xscale','log');
set(gca,'Yscale','log');
axis([0.01,48,0.005,500]);

plot([4,4]/60,[0.01,100],'k-');
plot([120,120]/60,[0.01,100],'k-');
plot([4,120]/60,[100,100],'k-');
plot([4,120]/60,[0.01,0.01],'k-');

axis square;
box on;

xlabel('Time (h)');
ylabel('Relative gene expression');